# Generated by Django 4.2.10 on 2024-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=35)),
                ('phonenumber', models.CharField(max_length=11)),
                ('instrumenttype', models.CharField(max_length=80)),
            ],
        ),
    ]
